// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SABZ.Infrastructure.Persistence;

#nullable disable

namespace SABZ.Infrastructure.Migrations
{
    [DbContext(typeof(SabzDbContext))]
    [Migration("20260821122810_AddCropRecommendationFoundation")]
    partial class AddCropRecommendationFoundation
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SABZ.Domain.Entities.Crop", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("CropCatalogId")
                        .HasColumnType("int");

                    b.Property<string>("CropName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<Guid>("FarmId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("GrowthStage")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("HarvestDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("PlantingDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("PreviousCrop")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Season")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("Active");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CropCatalogId");

                    b.HasIndex("FarmId");

                    b.ToTable("Crops");
                });

            modelBuilder.Entity("SABZ.Domain.Entities.CropCatalog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("ScientificName")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.HasKey("Id");

                    b.ToTable("CropCatalog");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = "Cereal",
                            Description = "Staple Rabi cereal crop, primary food grain of Pakistan.",
                            Name = "Wheat",
                            ScientificName = "Triticum aestivum"
                        },
                        new
                        {
                            Id = 2,
                            Category = "Cereal",
                            Description = "Major Kharif cereal, key export crop especially Basmati varieties.",
                            Name = "Rice",
                            ScientificName = "Oryza sativa"
                        },
                        new
                        {
                            Id = 3,
                            Category = "Fiber",
                            Description = "Primary fiber crop and backbone of Pakistan's textile industry.",
                            Name = "Cotton",
                            ScientificName = "Gossypium hirsutum"
                        },
                        new
                        {
                            Id = 4,
                            Category = "Cash Crop",
                            Description = "Major Kharif cash crop for sugar production.",
                            Name = "Sugarcane",
                            ScientificName = "Saccharum officinarum"
                        },
                        new
                        {
                            Id = 5,
                            Category = "Cereal",
                            Description = "Versatile cereal used for food, feed, and industry.",
                            Name = "Maize",
                            ScientificName = "Zea mays"
                        },
                        new
                        {
                            Id = 6,
                            Category = "Vegetable",
                            Description = "Important Rabi vegetable crop.",
                            Name = "Potato",
                            ScientificName = "Solanum tuberosum"
                        },
                        new
                        {
                            Id = 7,
                            Category = "Vegetable",
                            Description = "Widely cultivated vegetable across all provinces.",
                            Name = "Tomato",
                            ScientificName = "Solanum lycopersicum"
                        },
                        new
                        {
                            Id = 8,
                            Category = "Vegetable",
                            Description = "Essential vegetable crop grown in both Rabi and Kharif seasons.",
                            Name = "Onion",
                            ScientificName = "Allium cepa"
                        },
                        new
                        {
                            Id = 9,
                            Category = "Spice",
                            Description = "Major spice crop, Sindh is the largest producer.",
                            Name = "Chili Pepper",
                            ScientificName = "Capsicum annuum"
                        },
                        new
                        {
                            Id = 10,
                            Category = "Fruit",
                            Description = "Premium fruit crop, Multan and Sindh are major growing areas.",
                            Name = "Mango",
                            ScientificName = "Mangifera indica"
                        },
                        new
                        {
                            Id = 11,
                            Category = "Fruit",
                            Description = "Kinnow mandarin is a major export fruit from Punjab.",
                            Name = "Citrus",
                            ScientificName = "Citrus reticulata"
                        },
                        new
                        {
                            Id = 12,
                            Category = "Pulse",
                            Description = "Important Rabi pulse crop for protein.",
                            Name = "Gram (Chickpea)",
                            ScientificName = "Cicer arietinum"
                        },
                        new
                        {
                            Id = 13,
                            Category = "Pulse",
                            Description = "Rabi pulse widely grown in rainfed areas.",
                            Name = "Lentil",
                            ScientificName = "Lens culinaris"
                        },
                        new
                        {
                            Id = 14,
                            Category = "Oilseed",
                            Description = "Rabi oilseed crop.",
                            Name = "Mustard",
                            ScientificName = "Brassica campestris"
                        },
                        new
                        {
                            Id = 15,
                            Category = "Oilseed",
                            Description = "Oilseed crop suitable for both Rabi and Kharif.",
                            Name = "Sunflower",
                            ScientificName = "Helianthus annuus"
                        },
                        new
                        {
                            Id = 16,
                            Category = "Oilseed",
                            Description = "Kharif oilseed crop, primarily grown in Punjab and KP.",
                            Name = "Groundnut",
                            ScientificName = "Arachis hypogaea"
                        },
                        new
                        {
                            Id = 17,
                            Category = "Cash Crop",
                            Description = "Cash crop primarily grown in KP.",
                            Name = "Tobacco",
                            ScientificName = "Nicotiana tabacum"
                        },
                        new
                        {
                            Id = 18,
                            Category = "Fruit",
                            Description = "Important fruit crop of Sindh and Balochistan.",
                            Name = "Date Palm",
                            ScientificName = "Phoenix dactylifera"
                        },
                        new
                        {
                            Id = 19,
                            Category = "Fruit",
                            Description = "Major fruit crop of Balochistan and northern areas.",
                            Name = "Apple",
                            ScientificName = "Malus domestica"
                        },
                        new
                        {
                            Id = 20,
                            Category = "Cereal",
                            Description = "Rabi cereal, used for animal feed and food.",
                            Name = "Barley",
                            ScientificName = "Hordeum vulgare"
                        },
                        new
                        {
                            Id = 21,
                            Category = "Pulse",
                            Description = "Short-duration Kharif pulse, popular as catch crop and soil improver.",
                            Name = "Mung bean",
                            ScientificName = "Vigna radiata"
                        },
                        new
                        {
                            Id = 22,
                            Category = "Pulse",
                            Description = "Heat-tolerant Kharif pulse grown in Punjab and Sindh.",
                            Name = "Mash bean",
                            ScientificName = "Vigna mungo"
                        });
                });

            modelBuilder.Entity("SABZ.Domain.Entities.CropChangeRule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Effect")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Explanation")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("NextCategory")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PreviousCategory")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Source")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id");

                    b.HasIndex("PreviousCategory", "NextCategory")
                        .IsUnique();

                    b.ToTable("CropChangeRules");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Effect = "Positive",
                            Explanation = "Pulses are generally considered to leave residual soil nitrogen, which commonly benefits a following cereal crop.",
                            IsActive = true,
                            NextCategory = "Cereal",
                            PreviousCategory = "Pulse",
                            Source = "Initial SABZ crop-change reference dataset (general agronomic knowledge, expert review recommended)"
                        },
                        new
                        {
                            Id = 2,
                            Effect = "Positive",
                            Explanation = "Alternating cereals with pulses is widely considered sound rotation practice; pulses help maintain soil nitrogen.",
                            IsActive = true,
                            NextCategory = "Pulse",
                            PreviousCategory = "Cereal",
                            Source = "Initial SABZ crop-change reference dataset (general agronomic knowledge, expert review recommended)"
                        },
                        new
                        {
                            Id = 3,
                            Effect = "Caution",
                            Explanation = "Repeated cereal cropping can build up similar pests/diseases and draw on the same nutrients; rotating with a different crop group is commonly advised.",
                            IsActive = true,
                            NextCategory = "Cereal",
                            PreviousCategory = "Cereal",
                            Source = "Initial SABZ crop-change reference dataset (general agronomic knowledge, expert review recommended)"
                        },
                        new
                        {
                            Id = 4,
                            Effect = "Caution",
                            Explanation = "Growing vegetables back-to-back can increase pest and disease carry-over; rotating with a different crop group is commonly advised.",
                            IsActive = true,
                            NextCategory = "Vegetable",
                            PreviousCategory = "Vegetable",
                            Source = "Initial SABZ crop-change reference dataset (general agronomic knowledge, expert review recommended)"
                        },
                        new
                        {
                            Id = 5,
                            Effect = "Caution",
                            Explanation = "Consecutive pulse crops can build up pulse-specific diseases; alternating with another crop group is commonly advised.",
                            IsActive = true,
                            NextCategory = "Pulse",
                            PreviousCategory = "Pulse",
                            Source = "Initial SABZ crop-change reference dataset (general agronomic knowledge, expert review recommended)"
                        },
                        new
                        {
                            Id = 6,
                            Effect = "Positive",
                            Explanation = "Oilseeds are generally considered a good preceding crop for cereals due to different rooting and nutrient use.",
                            IsActive = true,
                            NextCategory = "Cereal",
                            PreviousCategory = "Oilseed",
                            Source = "Initial SABZ crop-change reference dataset (general agronomic knowledge, expert review recommended)"
                        });
                });

            modelBuilder.Entity("SABZ.Domain.Entities.CropRequirement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CropCatalogId")
                        .HasColumnType("int");

                    b.Property<int?>("GrowingDurationDays")
                        .HasColumnType("int");

                    b.Property<decimal?>("MaxTempC")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.Property<decimal?>("MinTempC")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.Property<string>("Season")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Source")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("SuitableSoils")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("WaterRequirement")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("CropCatalogId");

                    b.ToTable("CropRequirements");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CropCatalogId = 1,
                            GrowingDurationDays = 150,
                            MaxTempC = 25m,
                            MinTempC = 3m,
                            Season = "Rabi",
                            Source = "Initial SABZ suitability dataset (general agronomic knowledge, expert review recommended)",
                            SuitableSoils = "Loam,Loamy,Clay Loam,Sandy Loam,Alluvial",
                            WaterRequirement = "Medium"
                        },
                        new
                        {
                            Id = 2,
                            CropCatalogId = 2,
                            GrowingDurationDays = 130,
                            MaxTempC = 37m,
                            MinTempC = 20m,
                            Season = "Kharif",
                            Source = "Initial SABZ suitability dataset (general agronomic knowledge, expert review recommended)",
                            SuitableSoils = "Clay,Clay Loam,Alluvial,Loam,Loamy",
                            WaterRequirement = "High"
                        },
                        new
                        {
                            Id = 3,
                            CropCatalogId = 5,
                            GrowingDurationDays = 110,
                            MaxTempC = 35m,
                            MinTempC = 15m,
                            Season = "Kharif",
                            Source = "Initial SABZ suitability dataset (general agronomic knowledge, expert review recommended)",
                            SuitableSoils = "Loam,Loamy,Sandy Loam,Well-Drained",
                            WaterRequirement = "Medium"
                        },
                        new
                        {
                            Id = 4,
                            CropCatalogId = 3,
                            GrowingDurationDays = 160,
                            MaxTempC = 40m,
                            MinTempC = 20m,
                            Season = "Kharif",
                            Source = "Initial SABZ suitability dataset (general agronomic knowledge, expert review recommended)",
                            SuitableSoils = "Loam,Loamy,Sandy Loam,Alluvial",
                            WaterRequirement = "High"
                        },
                        new
                        {
                            Id = 5,
                            CropCatalogId = 4,
                            GrowingDurationDays = 330,
                            MaxTempC = 38m,
                            MinTempC = 20m,
                            Season = "Kharif",
                            Source = "Initial SABZ suitability dataset (general agronomic knowledge, expert review recommended)",
                            SuitableSoils = "Loam,Loamy,Clay Loam,Alluvial",
                            WaterRequirement = "High"
                        },
                        new
                        {
                            Id = 6,
                            CropCatalogId = 12,
                            GrowingDurationDays = 110,
                            MaxTempC = 28m,
                            MinTempC = 5m,
                            Season = "Rabi",
                            Source = "Initial SABZ suitability dataset (general agronomic knowledge, expert review recommended)",
                            SuitableSoils = "Loam,Loamy,Sandy Loam,Clay Loam",
                            WaterRequirement = "Low"
                        },
                        new
                        {
                            Id = 7,
                            CropCatalogId = 13,
                            GrowingDurationDays = 120,
                            MaxTempC = 27m,
                            MinTempC = 4m,
                            Season = "Rabi",
                            Source = "Initial SABZ suitability dataset (general agronomic knowledge, expert review recommended)",
                            SuitableSoils = "Loam,Loamy,Sandy Loam,Clay Loam",
                            WaterRequirement = "Low"
                        },
                        new
                        {
                            Id = 8,
                            CropCatalogId = 21,
                            GrowingDurationDays = 70,
                            MaxTempC = 38m,
                            MinTempC = 20m,
                            Season = "Kharif",
                            Source = "Initial SABZ suitability dataset (general agronomic knowledge, expert review recommended)",
                            SuitableSoils = "Loam,Loamy,Sandy Loam",
                            WaterRequirement = "Low"
                        },
                        new
                        {
                            Id = 9,
                            CropCatalogId = 22,
                            GrowingDurationDays = 80,
                            MaxTempC = 40m,
                            MinTempC = 20m,
                            Season = "Kharif",
                            Source = "Initial SABZ suitability dataset (general agronomic knowledge, expert review recommended)",
                            SuitableSoils = "Sandy Loam,Loam,Loamy",
                            WaterRequirement = "Low"
                        });
                });

            modelBuilder.Entity("SABZ.Domain.Entities.District", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("NameUrdu")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("ProvinceId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProvinceId");

                    b.ToTable("Districts");
                });

            modelBuilder.Entity("SABZ.Domain.Entities.Farm", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("DistrictId")
                        .HasColumnType("int");

                    b.Property<string>("FarmName")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<decimal>("FarmSize")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<string>("FarmSizeUnit")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("IrrigationType")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal?>("Latitude")
                        .HasPrecision(18, 10)
                        .HasColumnType("decimal(18,10)");

                    b.Property<decimal?>("Longitude")
                        .HasPrecision(18, 10)
                        .HasColumnType("decimal(18,10)");

                    b.Property<int>("ProvinceId")
                        .HasColumnType("int");

                    b.Property<string>("SoilType")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("TehsilId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("DistrictId");

                    b.HasIndex("ProvinceId");

                    b.HasIndex("TehsilId");

                    b.HasIndex("UserId");

                    b.ToTable("Farms");
                });

            modelBuilder.Entity("SABZ.Domain.Entities.Province", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("NameUrdu")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.ToTable("Provinces");
                });

            modelBuilder.Entity("SABZ.Domain.Entities.RegionalCropSuitability", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CropCatalogId")
                        .HasColumnType("int");

                    b.Property<int?>("DistrictId")
                        .HasColumnType("int");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("ProvinceId")
                        .HasColumnType("int");

                    b.Property<string>("Season")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Source")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("SuitabilityLevel")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("SuitabilityScore")
                        .HasColumnType("int");

                    b.Property<int?>("TehsilId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CropCatalogId");

                    b.HasIndex("DistrictId");

                    b.HasIndex("ProvinceId");

                    b.HasIndex("TehsilId");

                    b.ToTable("RegionalCropSuitabilities");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CropCatalogId = 1,
                            DistrictId = 102,
                            Notes = "Faisalabad is in the heart of Punjab's wheat belt with fertile alluvial soil.",
                            ProvinceId = 1,
                            Season = "Rabi",
                            Source = "PARC/FAO crop-zone data (general agronomic knowledge, not prescriptive advice)",
                            SuitabilityLevel = "Very High",
                            SuitabilityScore = 9
                        },
                        new
                        {
                            Id = 2,
                            CropCatalogId = 1,
                            DistrictId = 105,
                            Notes = "Sahiwal division is a major wheat producing region.",
                            ProvinceId = 1,
                            Season = "Rabi",
                            Source = "PARC/FAO crop-zone data (general agronomic knowledge, not prescriptive advice)",
                            SuitabilityLevel = "Very High",
                            SuitabilityScore = 9
                        },
                        new
                        {
                            Id = 3,
                            CropCatalogId = 1,
                            DistrictId = 104,
                            Notes = "Southern Punjab wheat with irrigation support.",
                            ProvinceId = 1,
                            Season = "Rabi",
                            Source = "PARC/FAO crop-zone data (general agronomic knowledge, not prescriptive advice)",
                            SuitabilityLevel = "High",
                            SuitabilityScore = 8
                        },
                        new
                        {
                            Id = 4,
                            CropCatalogId = 1,
                            DistrictId = 101,
                            Notes = "Lahore district grows wheat on irrigated alluvial soils.",
                            ProvinceId = 1,
                            Season = "Rabi",
                            Source = "PARC/FAO crop-zone data (general agronomic knowledge, not prescriptive advice)",
                            SuitabilityLevel = "High",
                            SuitabilityScore = 8
                        },
                        new
                        {
                            Id = 5,
                            CropCatalogId = 1,
                            DistrictId = 103,
                            Notes = "Rawalpindi grows wheat in the Potohar rainfed/irrigated mix.",
                            ProvinceId = 1,
                            Season = "Rabi",
                            Source = "PARC/FAO crop-zone data (general agronomic knowledge, not prescriptive advice)",
                            SuitabilityLevel = "High",
                            SuitabilityScore = 7
                        },
                        new
                        {
                            Id = 6,
                            CropCatalogId = 2,
                            DistrictId = 106,
                            Notes = "Sialkot-Gujranwala belt is famous for Basmati rice.",
                            ProvinceId = 1,
                            Season = "Kharif",
                            Source = "PARC/FAO crop-zone data (general agronomic knowledge, not prescriptive advice)",
                            SuitabilityLevel = "Very High",
                            SuitabilityScore = 9
                        },
                        new
                        {
                            Id = 7,
                            CropCatalogId = 2,
                            DistrictId = 107,
                            Notes = "Gujranwala is a major rice growing district.",
                            ProvinceId = 1,
                            Season = "Kharif",
                            Source = "PARC/FAO crop-zone data (general agronomic knowledge, not prescriptive advice)",
                            SuitabilityLevel = "Very High",
                            SuitabilityScore = 9
                        },
                        new
                        {
                            Id = 8,
                            CropCatalogId = 3,
                            DistrictId = 104,
                            Notes = "Multan is in Pakistan's cotton belt.",
                            ProvinceId = 1,
                            Season = "Kharif",
                            Source = "PARC/FAO crop-zone data (general agronomic knowledge, not prescriptive advice)",
                            SuitabilityLevel = "Very High",
                            SuitabilityScore = 9
                        },
                        new
                        {
                            Id = 9,
                            CropCatalogId = 3,
                            DistrictId = 108,
                            Notes = "Bahawalpur division is a major cotton area.",
                            ProvinceId = 1,
                            Season = "Kharif",
                            Source = "PARC/FAO crop-zone data (general agronomic knowledge, not prescriptive advice)",
                            SuitabilityLevel = "Very High",
                            SuitabilityScore = 9
                        },
                        new
                        {
                            Id = 10,
                            CropCatalogId = 3,
                            DistrictId = 105,
                            Notes = "Sahiwal has good cotton suitability.",
                            ProvinceId = 1,
                            Season = "Kharif",
                            Source = "PARC/FAO crop-zone data (general agronomic knowledge, not prescriptive advice)",
                            SuitabilityLevel = "High",
                            SuitabilityScore = 8
                        },
                        new
                        {
                            Id = 11,
                            CropCatalogId = 4,
                            DistrictId = 102,
                            Notes = "Faisalabad region has multiple sugar mills nearby.",
                            ProvinceId = 1,
                            Season = "Kharif",
                            Source = "PARC/FAO crop-zone data (general agronomic knowledge, not prescriptive advice)",
                            SuitabilityLevel = "High",
                            SuitabilityScore = 8
                        },
                        new
                        {
                            Id = 12,
                            CropCatalogId = 4,
                            DistrictId = 109,
                            Notes = "Jhang has good sugarcane growing conditions.",
                            ProvinceId = 1,
                            Season = "Kharif",
                            Source = "PARC/FAO crop-zone data (general agronomic knowledge, not prescriptive advice)",
                            SuitabilityLevel = "High",
                            SuitabilityScore = 7
                        },
                        new
                        {
                            Id = 13,
                            CropCatalogId = 12,
                            DistrictId = 103,
                            Notes = "Potohar tract (Rawalpindi) is a traditional gram growing area.",
                            ProvinceId = 1,
                            Season = "Rabi",
                            Source = "PARC/FAO crop-zone data (general agronomic knowledge, not prescriptive advice)",
                            SuitabilityLevel = "High",
                            SuitabilityScore = 8
                        },
                        new
                        {
                            Id = 14,
                            CropCatalogId = 12,
                            DistrictId = 109,
                            Notes = "Jhang supports gram on lighter soils.",
                            ProvinceId = 1,
                            Season = "Rabi",
                            Source = "PARC/FAO crop-zone data (general agronomic knowledge, not prescriptive advice)",
                            SuitabilityLevel = "High",
                            SuitabilityScore = 7
                        },
                        new
                        {
                            Id = 15,
                            CropCatalogId = 13,
                            DistrictId = 103,
                            Notes = "Rainfed Potohar areas grow lentil (masoor).",
                            ProvinceId = 1,
                            Season = "Rabi",
                            Source = "PARC/FAO crop-zone data (general agronomic knowledge, not prescriptive advice)",
                            SuitabilityLevel = "High",
                            SuitabilityScore = 7
                        },
                        new
                        {
                            Id = 16,
                            CropCatalogId = 21,
                            DistrictId = 108,
                            Notes = "Southern Punjab grows mung bean as a short Kharif pulse.",
                            ProvinceId = 1,
                            Season = "Kharif",
                            Source = "PARC/FAO crop-zone data (general agronomic knowledge, not prescriptive advice)",
                            SuitabilityLevel = "High",
                            SuitabilityScore = 7
                        },
                        new
                        {
                            Id = 17,
                            CropCatalogId = 22,
                            DistrictId = 104,
                            Notes = "Multan region supports heat-tolerant mash bean.",
                            ProvinceId = 1,
                            Season = "Kharif",
                            Source = "PARC/FAO crop-zone data (general agronomic knowledge, not prescriptive advice)",
                            SuitabilityLevel = "High",
                            SuitabilityScore = 7
                        },
                        new
                        {
                            Id = 18,
                            CropCatalogId = 2,
                            DistrictId = 243,
                            Notes = "Larkana is famous for Sindh rice varieties.",
                            ProvinceId = 7,
                            Season = "Kharif",
                            Source = "PARC/FAO crop-zone data (general agronomic knowledge, not prescriptive advice)",
                            SuitabilityLevel = "Very High",
                            SuitabilityScore = 9
                        },
                        new
                        {
                            Id = 19,
                            CropCatalogId = 2,
                            DistrictId = 254,
                            Notes = "Sukkur barrage supports rice cultivation.",
                            ProvinceId = 7,
                            Season = "Kharif",
                            Source = "PARC/FAO crop-zone data (general agronomic knowledge, not prescriptive advice)",
                            SuitabilityLevel = "High",
                            SuitabilityScore = 7
                        },
                        new
                        {
                            Id = 20,
                            CropCatalogId = 3,
                            DistrictId = 250,
                            Notes = "Shaheed Benazir Abad (Nawabshah) area supports cotton growing.",
                            ProvinceId = 7,
                            Season = "Kharif",
                            Source = "PARC/FAO crop-zone data (general agronomic knowledge, not prescriptive advice)",
                            SuitabilityLevel = "High",
                            SuitabilityScore = 7
                        },
                        new
                        {
                            Id = 21,
                            CropCatalogId = 4,
                            DistrictId = 232,
                            Notes = "Badin has sugar mills and sugarcane farms.",
                            ProvinceId = 7,
                            Season = "Kharif",
                            Source = "PARC/FAO crop-zone data (general agronomic knowledge, not prescriptive advice)",
                            SuitabilityLevel = "High",
                            SuitabilityScore = 8
                        },
                        new
                        {
                            Id = 22,
                            CropCatalogId = 21,
                            DistrictId = 232,
                            Notes = "Badin grows mung bean on coastal plain soils.",
                            ProvinceId = 7,
                            Season = "Kharif",
                            Source = "PARC/FAO crop-zone data (general agronomic knowledge, not prescriptive advice)",
                            SuitabilityLevel = "High",
                            SuitabilityScore = 7
                        },
                        new
                        {
                            Id = 23,
                            CropCatalogId = 5,
                            DistrictId = 228,
                            Notes = "Swat valley is a major maize growing area.",
                            ProvinceId = 6,
                            Season = "Kharif",
                            Source = "PARC/FAO crop-zone data (general agronomic knowledge, not prescriptive advice)",
                            SuitabilityLevel = "Very High",
                            SuitabilityScore = 9
                        },
                        new
                        {
                            Id = 24,
                            CropCatalogId = 5,
                            DistrictId = 219,
                            Notes = "Mardan supports maize cultivation.",
                            ProvinceId = 6,
                            Season = "Kharif",
                            Source = "PARC/FAO crop-zone data (general agronomic knowledge, not prescriptive advice)",
                            SuitabilityLevel = "High",
                            SuitabilityScore = 8
                        },
                        new
                        {
                            Id = 25,
                            CropCatalogId = 1,
                            DistrictId = 224,
                            Notes = "Peshawar valley supports wheat cultivation.",
                            ProvinceId = 6,
                            Season = "Rabi",
                            Source = "PARC/FAO crop-zone data (general agronomic knowledge, not prescriptive advice)",
                            SuitabilityLevel = "High",
                            SuitabilityScore = 7
                        },
                        new
                        {
                            Id = 26,
                            CropCatalogId = 1,
                            DistrictId = 219,
                            Notes = "Mardan has good wheat growing conditions.",
                            ProvinceId = 6,
                            Season = "Rabi",
                            Source = "PARC/FAO crop-zone data (general agronomic knowledge, not prescriptive advice)",
                            SuitabilityLevel = "High",
                            SuitabilityScore = 7
                        },
                        new
                        {
                            Id = 27,
                            CropCatalogId = 1,
                            DistrictId = 177,
                            Notes = "Sibi has moderate wheat suitability with irrigation.",
                            ProvinceId = 3,
                            Season = "Rabi",
                            Source = "PARC/FAO crop-zone data (general agronomic knowledge, not prescriptive advice)",
                            SuitabilityLevel = "Moderate",
                            SuitabilityScore = 5
                        },
                        new
                        {
                            Id = 28,
                            CropCatalogId = 1,
                            Notes = "Punjab is Pakistan's largest wheat producing province.",
                            ProvinceId = 1,
                            Season = "Rabi",
                            Source = "PARC/FAO crop-zone data (general agronomic knowledge, not prescriptive advice)",
                            SuitabilityLevel = "High",
                            SuitabilityScore = 8
                        },
                        new
                        {
                            Id = 29,
                            CropCatalogId = 2,
                            Notes = "Punjab grows rice widely in the central and northeast belts.",
                            ProvinceId = 1,
                            Season = "Kharif",
                            Source = "PARC/FAO crop-zone data (general agronomic knowledge, not prescriptive advice)",
                            SuitabilityLevel = "High",
                            SuitabilityScore = 7
                        },
                        new
                        {
                            Id = 30,
                            CropCatalogId = 5,
                            Notes = "Punjab grows maize but KP is the leading province.",
                            ProvinceId = 1,
                            Season = "Kharif",
                            Source = "PARC/FAO crop-zone data (general agronomic knowledge, not prescriptive advice)",
                            SuitabilityLevel = "Moderate",
                            SuitabilityScore = 6
                        },
                        new
                        {
                            Id = 31,
                            CropCatalogId = 3,
                            Notes = "Southern and central Punjab form the national cotton belt.",
                            ProvinceId = 1,
                            Season = "Kharif",
                            Source = "PARC/FAO crop-zone data (general agronomic knowledge, not prescriptive advice)",
                            SuitabilityLevel = "High",
                            SuitabilityScore = 8
                        },
                        new
                        {
                            Id = 32,
                            CropCatalogId = 4,
                            Notes = "Punjab is the main sugarcane producing province.",
                            ProvinceId = 1,
                            Season = "Kharif",
                            Source = "PARC/FAO crop-zone data (general agronomic knowledge, not prescriptive advice)",
                            SuitabilityLevel = "High",
                            SuitabilityScore = 7
                        },
                        new
                        {
                            Id = 33,
                            CropCatalogId = 12,
                            Notes = "Punjab's rainfed tracts are traditional gram areas.",
                            ProvinceId = 1,
                            Season = "Rabi",
                            Source = "PARC/FAO crop-zone data (general agronomic knowledge, not prescriptive advice)",
                            SuitabilityLevel = "High",
                            SuitabilityScore = 7
                        },
                        new
                        {
                            Id = 34,
                            CropCatalogId = 13,
                            Notes = "Lentil is grown in northern Punjab rainfed areas.",
                            ProvinceId = 1,
                            Season = "Rabi",
                            Source = "PARC/FAO crop-zone data (general agronomic knowledge, not prescriptive advice)",
                            SuitabilityLevel = "Moderate",
                            SuitabilityScore = 6
                        },
                        new
                        {
                            Id = 35,
                            CropCatalogId = 21,
                            Notes = "Punjab is the main mung bean producing province.",
                            ProvinceId = 1,
                            Season = "Kharif",
                            Source = "PARC/FAO crop-zone data (general agronomic knowledge, not prescriptive advice)",
                            SuitabilityLevel = "High",
                            SuitabilityScore = 7
                        },
                        new
                        {
                            Id = 36,
                            CropCatalogId = 22,
                            Notes = "Mash bean is grown in southern Punjab.",
                            ProvinceId = 1,
                            Season = "Kharif",
                            Source = "PARC/FAO crop-zone data (general agronomic knowledge, not prescriptive advice)",
                            SuitabilityLevel = "Moderate",
                            SuitabilityScore = 6
                        },
                        new
                        {
                            Id = 37,
                            CropCatalogId = 2,
                            Notes = "Sindh grows rice extensively along the Indus.",
                            ProvinceId = 7,
                            Season = "Kharif",
                            Source = "PARC/FAO crop-zone data (general agronomic knowledge, not prescriptive advice)",
                            SuitabilityLevel = "High",
                            SuitabilityScore = 8
                        },
                        new
                        {
                            Id = 38,
                            CropCatalogId = 3,
                            Notes = "Sindh is a major cotton producing province.",
                            ProvinceId = 7,
                            Season = "Kharif",
                            Source = "PARC/FAO crop-zone data (general agronomic knowledge, not prescriptive advice)",
                            SuitabilityLevel = "High",
                            SuitabilityScore = 7
                        },
                        new
                        {
                            Id = 39,
                            CropCatalogId = 4,
                            Notes = "Sindh supports sugarcane near sugar mills.",
                            ProvinceId = 7,
                            Season = "Kharif",
                            Source = "PARC/FAO crop-zone data (general agronomic knowledge, not prescriptive advice)",
                            SuitabilityLevel = "High",
                            SuitabilityScore = 7
                        },
                        new
                        {
                            Id = 40,
                            CropCatalogId = 21,
                            Notes = "Sindh grows mung bean on lighter soils.",
                            ProvinceId = 7,
                            Season = "Kharif",
                            Source = "PARC/FAO crop-zone data (general agronomic knowledge, not prescriptive advice)",
                            SuitabilityLevel = "High",
                            SuitabilityScore = 7
                        },
                        new
                        {
                            Id = 41,
                            CropCatalogId = 5,
                            Notes = "KP is Pakistan's leading maize province.",
                            ProvinceId = 6,
                            Season = "Kharif",
                            Source = "PARC/FAO crop-zone data (general agronomic knowledge, not prescriptive advice)",
                            SuitabilityLevel = "High",
                            SuitabilityScore = 8
                        },
                        new
                        {
                            Id = 42,
                            CropCatalogId = 1,
                            Notes = "KP grows wheat in the Peshawar and southern valleys.",
                            ProvinceId = 6,
                            Season = "Rabi",
                            Source = "PARC/FAO crop-zone data (general agronomic knowledge, not prescriptive advice)",
                            SuitabilityLevel = "Moderate",
                            SuitabilityScore = 6
                        },
                        new
                        {
                            Id = 43,
                            CropCatalogId = 1,
                            Notes = "Balochistan grows wheat in irrigated highland areas.",
                            ProvinceId = 3,
                            Season = "Rabi",
                            Source = "PARC/FAO crop-zone data (general agronomic knowledge, not prescriptive advice)",
                            SuitabilityLevel = "Moderate",
                            SuitabilityScore = 5
                        },
                        new
                        {
                            Id = 44,
                            CropCatalogId = 12,
                            Notes = "Balochistan highlands support gram under rainfall.",
                            ProvinceId = 3,
                            Season = "Rabi",
                            Source = "PARC/FAO crop-zone data (general agronomic knowledge, not prescriptive advice)",
                            SuitabilityLevel = "Moderate",
                            SuitabilityScore = 5
                        });
                });

            modelBuilder.Entity("SABZ.Domain.Entities.Tehsil", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DistrictId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("NameUrdu")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("DistrictId");

                    b.ToTable("Tehsils");
                });

            modelBuilder.Entity("SABZ.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("Email")
                        .HasMaxLength(320)
                        .HasColumnType("nvarchar(320)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("PreferredLanguage")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("English");

                    b.Property<string>("Role")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("Farmer");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasFilter("[Email] IS NOT NULL");

                    b.HasIndex("PhoneNumber")
                        .IsUnique()
                        .HasFilter("[PhoneNumber] IS NOT NULL");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("SABZ.Domain.Entities.Crop", b =>
                {
                    b.HasOne("SABZ.Domain.Entities.CropCatalog", "CropCatalog")
                        .WithMany()
                        .HasForeignKey("CropCatalogId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("SABZ.Domain.Entities.Farm", "Farm")
                        .WithMany("Crops")
                        .HasForeignKey("FarmId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CropCatalog");

                    b.Navigation("Farm");
                });

            modelBuilder.Entity("SABZ.Domain.Entities.CropRequirement", b =>
                {
                    b.HasOne("SABZ.Domain.Entities.CropCatalog", "CropCatalog")
                        .WithMany()
                        .HasForeignKey("CropCatalogId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CropCatalog");
                });

            modelBuilder.Entity("SABZ.Domain.Entities.District", b =>
                {
                    b.HasOne("SABZ.Domain.Entities.Province", "Province")
                        .WithMany("Districts")
                        .HasForeignKey("ProvinceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Province");
                });

            modelBuilder.Entity("SABZ.Domain.Entities.Farm", b =>
                {
                    b.HasOne("SABZ.Domain.Entities.District", "District")
                        .WithMany()
                        .HasForeignKey("DistrictId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SABZ.Domain.Entities.Province", "Province")
                        .WithMany()
                        .HasForeignKey("ProvinceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SABZ.Domain.Entities.Tehsil", "Tehsil")
                        .WithMany()
                        .HasForeignKey("TehsilId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SABZ.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("District");

                    b.Navigation("Province");

                    b.Navigation("Tehsil");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SABZ.Domain.Entities.RegionalCropSuitability", b =>
                {
                    b.HasOne("SABZ.Domain.Entities.CropCatalog", "CropCatalog")
                        .WithMany("RegionalSuitabilities")
                        .HasForeignKey("CropCatalogId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SABZ.Domain.Entities.District", "District")
                        .WithMany()
                        .HasForeignKey("DistrictId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("SABZ.Domain.Entities.Province", "Province")
                        .WithMany()
                        .HasForeignKey("ProvinceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SABZ.Domain.Entities.Tehsil", "Tehsil")
                        .WithMany()
                        .HasForeignKey("TehsilId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("CropCatalog");

                    b.Navigation("District");

                    b.Navigation("Province");

                    b.Navigation("Tehsil");
                });

            modelBuilder.Entity("SABZ.Domain.Entities.Tehsil", b =>
                {
                    b.HasOne("SABZ.Domain.Entities.District", "District")
                        .WithMany("Tehsils")
                        .HasForeignKey("DistrictId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("District");
                });

            modelBuilder.Entity("SABZ.Domain.Entities.CropCatalog", b =>
                {
                    b.Navigation("RegionalSuitabilities");
                });

            modelBuilder.Entity("SABZ.Domain.Entities.District", b =>
                {
                    b.Navigation("Tehsils");
                });

            modelBuilder.Entity("SABZ.Domain.Entities.Farm", b =>
                {
                    b.Navigation("Crops");
                });

            modelBuilder.Entity("SABZ.Domain.Entities.Province", b =>
                {
                    b.Navigation("Districts");
                });
#pragma warning restore 612, 618
        }
    }
}
