// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SABZ.Infrastructure.Persistence;

#nullable disable

namespace SABZ.Infrastructure.Migrations
{
    [DbContext(typeof(SabzDbContext))]
    [Migration("20260820195229_AddFarmCropLocationHierarchy")]
    partial class AddFarmCropLocationHierarchy
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SABZ.Domain.Entities.Crop", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("CropCatalogId")
                        .HasColumnType("int");

                    b.Property<string>("CropName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<Guid>("FarmId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("GrowthStage")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("PlantingDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("PreviousCrop")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Season")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("Active");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CropCatalogId");

                    b.HasIndex("FarmId");

                    b.ToTable("Crops");
                });

            modelBuilder.Entity("SABZ.Domain.Entities.CropCatalog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("ScientificName")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.HasKey("Id");

                    b.ToTable("CropCatalog");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = "Cereal",
                            Description = "Staple Rabi cereal crop, primary food grain of Pakistan.",
                            Name = "Wheat",
                            ScientificName = "Triticum aestivum"
                        },
                        new
                        {
                            Id = 2,
                            Category = "Cereal",
                            Description = "Major Kharif cereal, key export crop especially Basmati varieties.",
                            Name = "Rice",
                            ScientificName = "Oryza sativa"
                        },
                        new
                        {
                            Id = 3,
                            Category = "Fiber",
                            Description = "Primary fiber crop and backbone of Pakistan's textile industry.",
                            Name = "Cotton",
                            ScientificName = "Gossypium hirsutum"
                        },
                        new
                        {
                            Id = 4,
                            Category = "Cash Crop",
                            Description = "Major Kharif cash crop for sugar production.",
                            Name = "Sugarcane",
                            ScientificName = "Saccharum officinarum"
                        },
                        new
                        {
                            Id = 5,
                            Category = "Cereal",
                            Description = "Versatile cereal used for food, feed, and industry.",
                            Name = "Maize",
                            ScientificName = "Zea mays"
                        },
                        new
                        {
                            Id = 6,
                            Category = "Vegetable",
                            Description = "Important Rabi vegetable crop.",
                            Name = "Potato",
                            ScientificName = "Solanum tuberosum"
                        },
                        new
                        {
                            Id = 7,
                            Category = "Vegetable",
                            Description = "Widely cultivated vegetable across all provinces.",
                            Name = "Tomato",
                            ScientificName = "Solanum lycopersicum"
                        },
                        new
                        {
                            Id = 8,
                            Category = "Vegetable",
                            Description = "Essential vegetable crop grown in both Rabi and Kharif seasons.",
                            Name = "Onion",
                            ScientificName = "Allium cepa"
                        },
                        new
                        {
                            Id = 9,
                            Category = "Spice",
                            Description = "Major spice crop, Sindh is the largest producer.",
                            Name = "Chili Pepper",
                            ScientificName = "Capsicum annuum"
                        },
                        new
                        {
                            Id = 10,
                            Category = "Fruit",
                            Description = "Premium fruit crop, Multan and Sindh are major growing areas.",
                            Name = "Mango",
                            ScientificName = "Mangifera indica"
                        },
                        new
                        {
                            Id = 11,
                            Category = "Fruit",
                            Description = "Kinnow mandarin is a major export fruit from Punjab.",
                            Name = "Citrus",
                            ScientificName = "Citrus reticulata"
                        },
                        new
                        {
                            Id = 12,
                            Category = "Pulse",
                            Description = "Important Rabi pulse crop for protein.",
                            Name = "Gram (Chickpea)",
                            ScientificName = "Cicer arietinum"
                        },
                        new
                        {
                            Id = 13,
                            Category = "Pulse",
                            Description = "Rabi pulse widely grown in rainfed areas.",
                            Name = "Lentil",
                            ScientificName = "Lens culinaris"
                        },
                        new
                        {
                            Id = 14,
                            Category = "Oilseed",
                            Description = "Rabi oilseed crop.",
                            Name = "Mustard",
                            ScientificName = "Brassica campestris"
                        },
                        new
                        {
                            Id = 15,
                            Category = "Oilseed",
                            Description = "Oilseed crop suitable for both Rabi and Kharif.",
                            Name = "Sunflower",
                            ScientificName = "Helianthus annuus"
                        },
                        new
                        {
                            Id = 16,
                            Category = "Oilseed",
                            Description = "Kharif oilseed crop, primarily grown in Punjab and KP.",
                            Name = "Groundnut",
                            ScientificName = "Arachis hypogaea"
                        },
                        new
                        {
                            Id = 17,
                            Category = "Cash Crop",
                            Description = "Cash crop primarily grown in KP.",
                            Name = "Tobacco",
                            ScientificName = "Nicotiana tabacum"
                        },
                        new
                        {
                            Id = 18,
                            Category = "Fruit",
                            Description = "Important fruit crop of Sindh and Balochistan.",
                            Name = "Date Palm",
                            ScientificName = "Phoenix dactylifera"
                        },
                        new
                        {
                            Id = 19,
                            Category = "Fruit",
                            Description = "Major fruit crop of Balochistan and northern areas.",
                            Name = "Apple",
                            ScientificName = "Malus domestica"
                        },
                        new
                        {
                            Id = 20,
                            Category = "Cereal",
                            Description = "Rabi cereal, used for animal feed and food.",
                            Name = "Barley",
                            ScientificName = "Hordeum vulgare"
                        });
                });

            modelBuilder.Entity("SABZ.Domain.Entities.District", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("NameUrdu")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("ProvinceId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProvinceId");

                    b.ToTable("Districts");

                    b.HasData(
                        new
                        {
                            Id = 101,
                            Name = "Lahore",
                            ProvinceId = 1
                        },
                        new
                        {
                            Id = 102,
                            Name = "Faisalabad",
                            ProvinceId = 1
                        },
                        new
                        {
                            Id = 103,
                            Name = "Rawalpindi",
                            ProvinceId = 1
                        },
                        new
                        {
                            Id = 104,
                            Name = "Multan",
                            ProvinceId = 1
                        },
                        new
                        {
                            Id = 105,
                            Name = "Sahiwal",
                            ProvinceId = 1
                        },
                        new
                        {
                            Id = 106,
                            Name = "Sialkot",
                            ProvinceId = 1
                        },
                        new
                        {
                            Id = 107,
                            Name = "Gujranwala",
                            ProvinceId = 1
                        },
                        new
                        {
                            Id = 108,
                            Name = "Bahawalpur",
                            ProvinceId = 1
                        },
                        new
                        {
                            Id = 109,
                            Name = "Jhang",
                            ProvinceId = 1
                        },
                        new
                        {
                            Id = 110,
                            Name = "Okara",
                            ProvinceId = 1
                        },
                        new
                        {
                            Id = 201,
                            Name = "Karachi South",
                            ProvinceId = 2
                        },
                        new
                        {
                            Id = 202,
                            Name = "Hyderabad",
                            ProvinceId = 2
                        },
                        new
                        {
                            Id = 203,
                            Name = "Sukkur",
                            ProvinceId = 2
                        },
                        new
                        {
                            Id = 204,
                            Name = "Larkana",
                            ProvinceId = 2
                        },
                        new
                        {
                            Id = 205,
                            Name = "Nawabshah",
                            ProvinceId = 2
                        },
                        new
                        {
                            Id = 206,
                            Name = "Mirpur Khas",
                            ProvinceId = 2
                        },
                        new
                        {
                            Id = 207,
                            Name = "Thatta",
                            ProvinceId = 2
                        },
                        new
                        {
                            Id = 208,
                            Name = "Badin",
                            ProvinceId = 2
                        },
                        new
                        {
                            Id = 301,
                            Name = "Peshawar",
                            ProvinceId = 3
                        },
                        new
                        {
                            Id = 302,
                            Name = "Mardan",
                            ProvinceId = 3
                        },
                        new
                        {
                            Id = 303,
                            Name = "Swat",
                            ProvinceId = 3
                        },
                        new
                        {
                            Id = 304,
                            Name = "Abbottabad",
                            ProvinceId = 3
                        },
                        new
                        {
                            Id = 305,
                            Name = "Dera Ismail Khan",
                            ProvinceId = 3
                        },
                        new
                        {
                            Id = 306,
                            Name = "Mansehra",
                            ProvinceId = 3
                        },
                        new
                        {
                            Id = 401,
                            Name = "Quetta",
                            ProvinceId = 4
                        },
                        new
                        {
                            Id = 402,
                            Name = "Gwadar",
                            ProvinceId = 4
                        },
                        new
                        {
                            Id = 403,
                            Name = "Khuzdar",
                            ProvinceId = 4
                        },
                        new
                        {
                            Id = 404,
                            Name = "Sibi",
                            ProvinceId = 4
                        },
                        new
                        {
                            Id = 405,
                            Name = "Turbat",
                            ProvinceId = 4
                        },
                        new
                        {
                            Id = 501,
                            Name = "Islamabad",
                            ProvinceId = 5
                        },
                        new
                        {
                            Id = 601,
                            Name = "Gilgit",
                            ProvinceId = 6
                        },
                        new
                        {
                            Id = 602,
                            Name = "Skardu",
                            ProvinceId = 6
                        },
                        new
                        {
                            Id = 701,
                            Name = "Muzaffarabad",
                            ProvinceId = 7
                        },
                        new
                        {
                            Id = 702,
                            Name = "Mirpur",
                            ProvinceId = 7
                        });
                });

            modelBuilder.Entity("SABZ.Domain.Entities.Farm", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("DistrictId")
                        .HasColumnType("int");

                    b.Property<string>("FarmName")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<decimal>("FarmSize")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<string>("FarmSizeUnit")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("IrrigationType")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal?>("Latitude")
                        .HasPrecision(18, 10)
                        .HasColumnType("decimal(18,10)");

                    b.Property<decimal?>("Longitude")
                        .HasPrecision(18, 10)
                        .HasColumnType("decimal(18,10)");

                    b.Property<int>("ProvinceId")
                        .HasColumnType("int");

                    b.Property<string>("SoilType")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("TehsilId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("DistrictId");

                    b.HasIndex("ProvinceId");

                    b.HasIndex("TehsilId");

                    b.HasIndex("UserId");

                    b.ToTable("Farms");
                });

            modelBuilder.Entity("SABZ.Domain.Entities.Province", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("NameUrdu")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.ToTable("Provinces");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Punjab",
                            NameUrdu = "پنجاب"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Sindh",
                            NameUrdu = "سندھ"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Khyber Pakhtunkhwa",
                            NameUrdu = "خیبر پختونخوا"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Balochistan",
                            NameUrdu = "بلوچستان"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Islamabad Capital Territory",
                            NameUrdu = "وفاقی دارالحکومت"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Gilgit-Baltistan",
                            NameUrdu = "گلگت بلتستان"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Azad Jammu and Kashmir",
                            NameUrdu = "آزاد جموں و کشمیر"
                        });
                });

            modelBuilder.Entity("SABZ.Domain.Entities.RegionalCropSuitability", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CropCatalogId")
                        .HasColumnType("int");

                    b.Property<int?>("DistrictId")
                        .HasColumnType("int");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("ProvinceId")
                        .HasColumnType("int");

                    b.Property<string>("Season")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Source")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("SuitabilityLevel")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("SuitabilityScore")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CropCatalogId");

                    b.HasIndex("DistrictId");

                    b.HasIndex("ProvinceId");

                    b.ToTable("RegionalCropSuitabilities");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CropCatalogId = 1,
                            DistrictId = 102,
                            Notes = "Faisalabad is in the heart of Punjab's wheat belt with fertile alluvial soil.",
                            ProvinceId = 1,
                            Season = "Rabi",
                            Source = "PARC/FAO crop-zone data (general agronomic knowledge, not prescriptive advice)",
                            SuitabilityLevel = "Very High",
                            SuitabilityScore = 9
                        },
                        new
                        {
                            Id = 2,
                            CropCatalogId = 1,
                            DistrictId = 105,
                            Notes = "Sahiwal division is a major wheat producing region.",
                            ProvinceId = 1,
                            Season = "Rabi",
                            Source = "PARC/FAO crop-zone data (general agronomic knowledge, not prescriptive advice)",
                            SuitabilityLevel = "Very High",
                            SuitabilityScore = 9
                        },
                        new
                        {
                            Id = 3,
                            CropCatalogId = 1,
                            DistrictId = 104,
                            Notes = "Southern Punjab wheat with irrigation support.",
                            ProvinceId = 1,
                            Season = "Rabi",
                            Source = "PARC/FAO crop-zone data (general agronomic knowledge, not prescriptive advice)",
                            SuitabilityLevel = "High",
                            SuitabilityScore = 8
                        },
                        new
                        {
                            Id = 4,
                            CropCatalogId = 2,
                            DistrictId = 106,
                            Notes = "Sialkot-Gujranwala belt is famous for Basmati rice.",
                            ProvinceId = 1,
                            Season = "Kharif",
                            Source = "PARC/FAO crop-zone data (general agronomic knowledge, not prescriptive advice)",
                            SuitabilityLevel = "Very High",
                            SuitabilityScore = 9
                        },
                        new
                        {
                            Id = 5,
                            CropCatalogId = 2,
                            DistrictId = 107,
                            Notes = "Gujranwala is a major rice growing district.",
                            ProvinceId = 1,
                            Season = "Kharif",
                            Source = "PARC/FAO crop-zone data (general agronomic knowledge, not prescriptive advice)",
                            SuitabilityLevel = "Very High",
                            SuitabilityScore = 9
                        },
                        new
                        {
                            Id = 6,
                            CropCatalogId = 3,
                            DistrictId = 104,
                            Notes = "Multan is in Pakistan's cotton belt.",
                            ProvinceId = 1,
                            Season = "Kharif",
                            Source = "PARC/FAO crop-zone data (general agronomic knowledge, not prescriptive advice)",
                            SuitabilityLevel = "Very High",
                            SuitabilityScore = 9
                        },
                        new
                        {
                            Id = 7,
                            CropCatalogId = 3,
                            DistrictId = 108,
                            Notes = "Bahawalpur division is a major cotton area.",
                            ProvinceId = 1,
                            Season = "Kharif",
                            Source = "PARC/FAO crop-zone data (general agronomic knowledge, not prescriptive advice)",
                            SuitabilityLevel = "Very High",
                            SuitabilityScore = 9
                        },
                        new
                        {
                            Id = 8,
                            CropCatalogId = 3,
                            DistrictId = 105,
                            Notes = "Sahiwal has good cotton suitability.",
                            ProvinceId = 1,
                            Season = "Kharif",
                            Source = "PARC/FAO crop-zone data (general agronomic knowledge, not prescriptive advice)",
                            SuitabilityLevel = "High",
                            SuitabilityScore = 8
                        },
                        new
                        {
                            Id = 9,
                            CropCatalogId = 4,
                            DistrictId = 102,
                            Notes = "Faisalabad region has multiple sugar mills nearby.",
                            ProvinceId = 1,
                            Season = "Kharif",
                            Source = "PARC/FAO crop-zone data (general agronomic knowledge, not prescriptive advice)",
                            SuitabilityLevel = "High",
                            SuitabilityScore = 8
                        },
                        new
                        {
                            Id = 10,
                            CropCatalogId = 4,
                            DistrictId = 109,
                            Notes = "Jhang has good sugarcane growing conditions.",
                            ProvinceId = 1,
                            Season = "Kharif",
                            Source = "PARC/FAO crop-zone data (general agronomic knowledge, not prescriptive advice)",
                            SuitabilityLevel = "High",
                            SuitabilityScore = 7
                        },
                        new
                        {
                            Id = 11,
                            CropCatalogId = 11,
                            DistrictId = 109,
                            Notes = "Jhang/Sargodha belt is world-famous for Kinnow mandarin.",
                            ProvinceId = 1,
                            Season = "Rabi",
                            Source = "PARC/FAO crop-zone data (general agronomic knowledge, not prescriptive advice)",
                            SuitabilityLevel = "Very High",
                            SuitabilityScore = 9
                        },
                        new
                        {
                            Id = 12,
                            CropCatalogId = 10,
                            DistrictId = 104,
                            Notes = "Multan is the mango capital of Pakistan.",
                            ProvinceId = 1,
                            Season = "Kharif",
                            Source = "PARC/FAO crop-zone data (general agronomic knowledge, not prescriptive advice)",
                            SuitabilityLevel = "Very High",
                            SuitabilityScore = 10
                        },
                        new
                        {
                            Id = 13,
                            CropCatalogId = 2,
                            DistrictId = 204,
                            Notes = "Larkana is famous for Sindh rice varieties.",
                            ProvinceId = 2,
                            Season = "Kharif",
                            Source = "PARC/FAO crop-zone data (general agronomic knowledge, not prescriptive advice)",
                            SuitabilityLevel = "Very High",
                            SuitabilityScore = 9
                        },
                        new
                        {
                            Id = 14,
                            CropCatalogId = 2,
                            DistrictId = 203,
                            Notes = "Sukkur barrage supports rice cultivation.",
                            ProvinceId = 2,
                            Season = "Kharif",
                            Source = "PARC/FAO crop-zone data (general agronomic knowledge, not prescriptive advice)",
                            SuitabilityLevel = "High",
                            SuitabilityScore = 7
                        },
                        new
                        {
                            Id = 15,
                            CropCatalogId = 3,
                            DistrictId = 205,
                            Notes = "Nawabshah area supports cotton growing.",
                            ProvinceId = 2,
                            Season = "Kharif",
                            Source = "PARC/FAO crop-zone data (general agronomic knowledge, not prescriptive advice)",
                            SuitabilityLevel = "High",
                            SuitabilityScore = 7
                        },
                        new
                        {
                            Id = 16,
                            CropCatalogId = 4,
                            DistrictId = 208,
                            Notes = "Badin has sugar mills and sugarcane farms.",
                            ProvinceId = 2,
                            Season = "Kharif",
                            Source = "PARC/FAO crop-zone data (general agronomic knowledge, not prescriptive advice)",
                            SuitabilityLevel = "High",
                            SuitabilityScore = 8
                        },
                        new
                        {
                            Id = 17,
                            CropCatalogId = 9,
                            DistrictId = 206,
                            Notes = "Mirpur Khas/Kunri is the chili capital of Pakistan.",
                            ProvinceId = 2,
                            Season = "Kharif",
                            Source = "PARC/FAO crop-zone data (general agronomic knowledge, not prescriptive advice)",
                            SuitabilityLevel = "Very High",
                            SuitabilityScore = 9
                        },
                        new
                        {
                            Id = 18,
                            CropCatalogId = 9,
                            DistrictId = 208,
                            Notes = "Badin is a major chili growing district.",
                            ProvinceId = 2,
                            Season = "Kharif",
                            Source = "PARC/FAO crop-zone data (general agronomic knowledge, not prescriptive advice)",
                            SuitabilityLevel = "High",
                            SuitabilityScore = 8
                        },
                        new
                        {
                            Id = 19,
                            CropCatalogId = 18,
                            DistrictId = 203,
                            Notes = "Sukkur/Khairpur is a major date producing region.",
                            ProvinceId = 2,
                            Season = "Kharif",
                            Source = "PARC/FAO crop-zone data (general agronomic knowledge, not prescriptive advice)",
                            SuitabilityLevel = "High",
                            SuitabilityScore = 8
                        },
                        new
                        {
                            Id = 20,
                            CropCatalogId = 5,
                            DistrictId = 303,
                            Notes = "Swat valley is a major maize growing area.",
                            ProvinceId = 3,
                            Season = "Kharif",
                            Source = "PARC/FAO crop-zone data (general agronomic knowledge, not prescriptive advice)",
                            SuitabilityLevel = "Very High",
                            SuitabilityScore = 9
                        },
                        new
                        {
                            Id = 21,
                            CropCatalogId = 5,
                            DistrictId = 302,
                            Notes = "Mardan supports maize cultivation.",
                            ProvinceId = 3,
                            Season = "Kharif",
                            Source = "PARC/FAO crop-zone data (general agronomic knowledge, not prescriptive advice)",
                            SuitabilityLevel = "High",
                            SuitabilityScore = 8
                        },
                        new
                        {
                            Id = 22,
                            CropCatalogId = 17,
                            DistrictId = 302,
                            Notes = "Mardan/Swat is the tobacco belt of Pakistan.",
                            ProvinceId = 3,
                            Season = "Kharif",
                            Source = "PARC/FAO crop-zone data (general agronomic knowledge, not prescriptive advice)",
                            SuitabilityLevel = "Very High",
                            SuitabilityScore = 9
                        },
                        new
                        {
                            Id = 23,
                            CropCatalogId = 17,
                            DistrictId = 303,
                            Notes = "Swat valley has tobacco farms.",
                            ProvinceId = 3,
                            Season = "Kharif",
                            Source = "PARC/FAO crop-zone data (general agronomic knowledge, not prescriptive advice)",
                            SuitabilityLevel = "High",
                            SuitabilityScore = 8
                        },
                        new
                        {
                            Id = 24,
                            CropCatalogId = 1,
                            DistrictId = 301,
                            Notes = "Peshawar valley supports wheat cultivation.",
                            ProvinceId = 3,
                            Season = "Rabi",
                            Source = "PARC/FAO crop-zone data (general agronomic knowledge, not prescriptive advice)",
                            SuitabilityLevel = "High",
                            SuitabilityScore = 7
                        },
                        new
                        {
                            Id = 25,
                            CropCatalogId = 1,
                            DistrictId = 302,
                            Notes = "Mardan has good wheat growing conditions.",
                            ProvinceId = 3,
                            Season = "Rabi",
                            Source = "PARC/FAO crop-zone data (general agronomic knowledge, not prescriptive advice)",
                            SuitabilityLevel = "High",
                            SuitabilityScore = 7
                        },
                        new
                        {
                            Id = 26,
                            CropCatalogId = 19,
                            DistrictId = 401,
                            Notes = "Quetta/Ziarat is famous for apple orchards.",
                            ProvinceId = 4,
                            Season = "Rabi",
                            Source = "PARC/FAO crop-zone data (general agronomic knowledge, not prescriptive advice)",
                            SuitabilityLevel = "Very High",
                            SuitabilityScore = 9
                        },
                        new
                        {
                            Id = 27,
                            CropCatalogId = 18,
                            DistrictId = 405,
                            Notes = "Turbat/Kech is a major date producing area.",
                            ProvinceId = 4,
                            Season = "Kharif",
                            Source = "PARC/FAO crop-zone data (general agronomic knowledge, not prescriptive advice)",
                            SuitabilityLevel = "High",
                            SuitabilityScore = 8
                        },
                        new
                        {
                            Id = 28,
                            CropCatalogId = 1,
                            DistrictId = 404,
                            Notes = "Sibi has moderate wheat suitability with irrigation.",
                            ProvinceId = 4,
                            Season = "Rabi",
                            Source = "PARC/FAO crop-zone data (general agronomic knowledge, not prescriptive advice)",
                            SuitabilityLevel = "Moderate",
                            SuitabilityScore = 5
                        });
                });

            modelBuilder.Entity("SABZ.Domain.Entities.Tehsil", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DistrictId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("NameUrdu")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("DistrictId");

                    b.ToTable("Tehsils");

                    b.HasData(
                        new
                        {
                            Id = 1001,
                            DistrictId = 101,
                            Name = "Lahore City"
                        },
                        new
                        {
                            Id = 1002,
                            DistrictId = 101,
                            Name = "Model Town"
                        },
                        new
                        {
                            Id = 1003,
                            DistrictId = 101,
                            Name = "Shalimar"
                        },
                        new
                        {
                            Id = 1004,
                            DistrictId = 102,
                            Name = "Faisalabad City"
                        },
                        new
                        {
                            Id = 1005,
                            DistrictId = 102,
                            Name = "Jaranwala"
                        },
                        new
                        {
                            Id = 1006,
                            DistrictId = 102,
                            Name = "Tandlianwala"
                        },
                        new
                        {
                            Id = 1007,
                            DistrictId = 103,
                            Name = "Rawalpindi"
                        },
                        new
                        {
                            Id = 1008,
                            DistrictId = 103,
                            Name = "Gujar Khan"
                        },
                        new
                        {
                            Id = 1009,
                            DistrictId = 103,
                            Name = "Taxila"
                        },
                        new
                        {
                            Id = 1010,
                            DistrictId = 104,
                            Name = "Multan City"
                        },
                        new
                        {
                            Id = 1011,
                            DistrictId = 104,
                            Name = "Shujabad"
                        },
                        new
                        {
                            Id = 1012,
                            DistrictId = 104,
                            Name = "Jalalpur Pirwala"
                        },
                        new
                        {
                            Id = 1013,
                            DistrictId = 105,
                            Name = "Sahiwal"
                        },
                        new
                        {
                            Id = 1014,
                            DistrictId = 105,
                            Name = "Chichawatni"
                        },
                        new
                        {
                            Id = 1015,
                            DistrictId = 106,
                            Name = "Sialkot"
                        },
                        new
                        {
                            Id = 1016,
                            DistrictId = 106,
                            Name = "Daska"
                        },
                        new
                        {
                            Id = 1017,
                            DistrictId = 106,
                            Name = "Pasrur"
                        },
                        new
                        {
                            Id = 1018,
                            DistrictId = 107,
                            Name = "Gujranwala City"
                        },
                        new
                        {
                            Id = 1019,
                            DistrictId = 107,
                            Name = "Kamoke"
                        },
                        new
                        {
                            Id = 1020,
                            DistrictId = 107,
                            Name = "Nowshera Virkan"
                        },
                        new
                        {
                            Id = 1021,
                            DistrictId = 108,
                            Name = "Bahawalpur City"
                        },
                        new
                        {
                            Id = 1022,
                            DistrictId = 108,
                            Name = "Yazman"
                        },
                        new
                        {
                            Id = 1023,
                            DistrictId = 108,
                            Name = "Ahmedpur East"
                        },
                        new
                        {
                            Id = 1024,
                            DistrictId = 109,
                            Name = "Jhang"
                        },
                        new
                        {
                            Id = 1025,
                            DistrictId = 109,
                            Name = "Chiniot"
                        },
                        new
                        {
                            Id = 1026,
                            DistrictId = 109,
                            Name = "Shorkot"
                        },
                        new
                        {
                            Id = 1027,
                            DistrictId = 110,
                            Name = "Okara"
                        },
                        new
                        {
                            Id = 1028,
                            DistrictId = 110,
                            Name = "Depalpur"
                        },
                        new
                        {
                            Id = 2001,
                            DistrictId = 201,
                            Name = "Saddar"
                        },
                        new
                        {
                            Id = 2002,
                            DistrictId = 201,
                            Name = "Clifton"
                        },
                        new
                        {
                            Id = 2003,
                            DistrictId = 202,
                            Name = "Hyderabad City"
                        },
                        new
                        {
                            Id = 2004,
                            DistrictId = 202,
                            Name = "Latifabad"
                        },
                        new
                        {
                            Id = 2005,
                            DistrictId = 202,
                            Name = "Qasimabad"
                        },
                        new
                        {
                            Id = 2006,
                            DistrictId = 203,
                            Name = "Sukkur City"
                        },
                        new
                        {
                            Id = 2007,
                            DistrictId = 203,
                            Name = "Rohri"
                        },
                        new
                        {
                            Id = 2008,
                            DistrictId = 204,
                            Name = "Larkana City"
                        },
                        new
                        {
                            Id = 2009,
                            DistrictId = 204,
                            Name = "Ratodero"
                        },
                        new
                        {
                            Id = 2010,
                            DistrictId = 205,
                            Name = "Nawabshah"
                        },
                        new
                        {
                            Id = 2011,
                            DistrictId = 205,
                            Name = "Daur"
                        },
                        new
                        {
                            Id = 2012,
                            DistrictId = 206,
                            Name = "Mirpur Khas"
                        },
                        new
                        {
                            Id = 2013,
                            DistrictId = 206,
                            Name = "Digri"
                        },
                        new
                        {
                            Id = 2014,
                            DistrictId = 207,
                            Name = "Thatta"
                        },
                        new
                        {
                            Id = 2015,
                            DistrictId = 207,
                            Name = "Mirpur Sakro"
                        },
                        new
                        {
                            Id = 2016,
                            DistrictId = 208,
                            Name = "Badin"
                        },
                        new
                        {
                            Id = 2017,
                            DistrictId = 208,
                            Name = "Tando Bago"
                        },
                        new
                        {
                            Id = 3001,
                            DistrictId = 301,
                            Name = "Peshawar City"
                        },
                        new
                        {
                            Id = 3002,
                            DistrictId = 301,
                            Name = "Peshawar Saddar"
                        },
                        new
                        {
                            Id = 3003,
                            DistrictId = 301,
                            Name = "Charsadda Road"
                        },
                        new
                        {
                            Id = 3004,
                            DistrictId = 302,
                            Name = "Mardan"
                        },
                        new
                        {
                            Id = 3005,
                            DistrictId = 302,
                            Name = "Takht-i-Bahi"
                        },
                        new
                        {
                            Id = 3006,
                            DistrictId = 303,
                            Name = "Mingora"
                        },
                        new
                        {
                            Id = 3007,
                            DistrictId = 303,
                            Name = "Kabal"
                        },
                        new
                        {
                            Id = 3008,
                            DistrictId = 303,
                            Name = "Barikot"
                        },
                        new
                        {
                            Id = 3009,
                            DistrictId = 304,
                            Name = "Abbottabad"
                        },
                        new
                        {
                            Id = 3010,
                            DistrictId = 304,
                            Name = "Havelian"
                        },
                        new
                        {
                            Id = 3011,
                            DistrictId = 305,
                            Name = "Dera Ismail Khan"
                        },
                        new
                        {
                            Id = 3012,
                            DistrictId = 305,
                            Name = "Kulachi"
                        },
                        new
                        {
                            Id = 3013,
                            DistrictId = 306,
                            Name = "Mansehra"
                        },
                        new
                        {
                            Id = 3014,
                            DistrictId = 306,
                            Name = "Balakot"
                        },
                        new
                        {
                            Id = 4001,
                            DistrictId = 401,
                            Name = "Quetta City"
                        },
                        new
                        {
                            Id = 4002,
                            DistrictId = 401,
                            Name = "Quetta Saddar"
                        },
                        new
                        {
                            Id = 4003,
                            DistrictId = 402,
                            Name = "Gwadar"
                        },
                        new
                        {
                            Id = 4004,
                            DistrictId = 402,
                            Name = "Pasni"
                        },
                        new
                        {
                            Id = 4005,
                            DistrictId = 403,
                            Name = "Khuzdar"
                        },
                        new
                        {
                            Id = 4006,
                            DistrictId = 403,
                            Name = "Wadh"
                        },
                        new
                        {
                            Id = 4007,
                            DistrictId = 404,
                            Name = "Sibi"
                        },
                        new
                        {
                            Id = 4008,
                            DistrictId = 405,
                            Name = "Turbat"
                        },
                        new
                        {
                            Id = 5001,
                            DistrictId = 501,
                            Name = "Islamabad"
                        },
                        new
                        {
                            Id = 6001,
                            DistrictId = 601,
                            Name = "Gilgit"
                        },
                        new
                        {
                            Id = 6002,
                            DistrictId = 602,
                            Name = "Skardu"
                        },
                        new
                        {
                            Id = 7001,
                            DistrictId = 701,
                            Name = "Muzaffarabad"
                        },
                        new
                        {
                            Id = 7002,
                            DistrictId = 702,
                            Name = "Mirpur"
                        });
                });

            modelBuilder.Entity("SABZ.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("Email")
                        .HasMaxLength(320)
                        .HasColumnType("nvarchar(320)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("PreferredLanguage")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("English");

                    b.Property<string>("Role")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("Farmer");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasFilter("[Email] IS NOT NULL");

                    b.HasIndex("PhoneNumber")
                        .IsUnique()
                        .HasFilter("[PhoneNumber] IS NOT NULL");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("SABZ.Domain.Entities.Crop", b =>
                {
                    b.HasOne("SABZ.Domain.Entities.CropCatalog", "CropCatalog")
                        .WithMany()
                        .HasForeignKey("CropCatalogId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("SABZ.Domain.Entities.Farm", "Farm")
                        .WithMany("Crops")
                        .HasForeignKey("FarmId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CropCatalog");

                    b.Navigation("Farm");
                });

            modelBuilder.Entity("SABZ.Domain.Entities.District", b =>
                {
                    b.HasOne("SABZ.Domain.Entities.Province", "Province")
                        .WithMany("Districts")
                        .HasForeignKey("ProvinceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Province");
                });

            modelBuilder.Entity("SABZ.Domain.Entities.Farm", b =>
                {
                    b.HasOne("SABZ.Domain.Entities.District", "District")
                        .WithMany()
                        .HasForeignKey("DistrictId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SABZ.Domain.Entities.Province", "Province")
                        .WithMany()
                        .HasForeignKey("ProvinceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SABZ.Domain.Entities.Tehsil", "Tehsil")
                        .WithMany()
                        .HasForeignKey("TehsilId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SABZ.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("District");

                    b.Navigation("Province");

                    b.Navigation("Tehsil");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SABZ.Domain.Entities.RegionalCropSuitability", b =>
                {
                    b.HasOne("SABZ.Domain.Entities.CropCatalog", "CropCatalog")
                        .WithMany("RegionalSuitabilities")
                        .HasForeignKey("CropCatalogId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SABZ.Domain.Entities.District", "District")
                        .WithMany()
                        .HasForeignKey("DistrictId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("SABZ.Domain.Entities.Province", "Province")
                        .WithMany()
                        .HasForeignKey("ProvinceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CropCatalog");

                    b.Navigation("District");

                    b.Navigation("Province");
                });

            modelBuilder.Entity("SABZ.Domain.Entities.Tehsil", b =>
                {
                    b.HasOne("SABZ.Domain.Entities.District", "District")
                        .WithMany("Tehsils")
                        .HasForeignKey("DistrictId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("District");
                });

            modelBuilder.Entity("SABZ.Domain.Entities.CropCatalog", b =>
                {
                    b.Navigation("RegionalSuitabilities");
                });

            modelBuilder.Entity("SABZ.Domain.Entities.District", b =>
                {
                    b.Navigation("Tehsils");
                });

            modelBuilder.Entity("SABZ.Domain.Entities.Farm", b =>
                {
                    b.Navigation("Crops");
                });

            modelBuilder.Entity("SABZ.Domain.Entities.Province", b =>
                {
                    b.Navigation("Districts");
                });
#pragma warning restore 612, 618
        }
    }
}
