// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SABZ.Infrastructure.Persistence;

#nullable disable

namespace SABZ.Infrastructure.Migrations
{
    [DbContext(typeof(SabzDbContext))]
    [Migration("20260820204141_ReplaceLocationDataWithCompleteDataset")]
    partial class ReplaceLocationDataWithCompleteDataset
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SABZ.Domain.Entities.Crop", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("CropCatalogId")
                        .HasColumnType("int");

                    b.Property<string>("CropName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<Guid>("FarmId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("GrowthStage")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("PlantingDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("PreviousCrop")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Season")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("Active");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CropCatalogId");

                    b.HasIndex("FarmId");

                    b.ToTable("Crops");
                });

            modelBuilder.Entity("SABZ.Domain.Entities.CropCatalog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("ScientificName")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.HasKey("Id");

                    b.ToTable("CropCatalog");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = "Cereal",
                            Description = "Staple Rabi cereal crop, primary food grain of Pakistan.",
                            Name = "Wheat",
                            ScientificName = "Triticum aestivum"
                        },
                        new
                        {
                            Id = 2,
                            Category = "Cereal",
                            Description = "Major Kharif cereal, key export crop especially Basmati varieties.",
                            Name = "Rice",
                            ScientificName = "Oryza sativa"
                        },
                        new
                        {
                            Id = 3,
                            Category = "Fiber",
                            Description = "Primary fiber crop and backbone of Pakistan's textile industry.",
                            Name = "Cotton",
                            ScientificName = "Gossypium hirsutum"
                        },
                        new
                        {
                            Id = 4,
                            Category = "Cash Crop",
                            Description = "Major Kharif cash crop for sugar production.",
                            Name = "Sugarcane",
                            ScientificName = "Saccharum officinarum"
                        },
                        new
                        {
                            Id = 5,
                            Category = "Cereal",
                            Description = "Versatile cereal used for food, feed, and industry.",
                            Name = "Maize",
                            ScientificName = "Zea mays"
                        },
                        new
                        {
                            Id = 6,
                            Category = "Vegetable",
                            Description = "Important Rabi vegetable crop.",
                            Name = "Potato",
                            ScientificName = "Solanum tuberosum"
                        },
                        new
                        {
                            Id = 7,
                            Category = "Vegetable",
                            Description = "Widely cultivated vegetable across all provinces.",
                            Name = "Tomato",
                            ScientificName = "Solanum lycopersicum"
                        },
                        new
                        {
                            Id = 8,
                            Category = "Vegetable",
                            Description = "Essential vegetable crop grown in both Rabi and Kharif seasons.",
                            Name = "Onion",
                            ScientificName = "Allium cepa"
                        },
                        new
                        {
                            Id = 9,
                            Category = "Spice",
                            Description = "Major spice crop, Sindh is the largest producer.",
                            Name = "Chili Pepper",
                            ScientificName = "Capsicum annuum"
                        },
                        new
                        {
                            Id = 10,
                            Category = "Fruit",
                            Description = "Premium fruit crop, Multan and Sindh are major growing areas.",
                            Name = "Mango",
                            ScientificName = "Mangifera indica"
                        },
                        new
                        {
                            Id = 11,
                            Category = "Fruit",
                            Description = "Kinnow mandarin is a major export fruit from Punjab.",
                            Name = "Citrus",
                            ScientificName = "Citrus reticulata"
                        },
                        new
                        {
                            Id = 12,
                            Category = "Pulse",
                            Description = "Important Rabi pulse crop for protein.",
                            Name = "Gram (Chickpea)",
                            ScientificName = "Cicer arietinum"
                        },
                        new
                        {
                            Id = 13,
                            Category = "Pulse",
                            Description = "Rabi pulse widely grown in rainfed areas.",
                            Name = "Lentil",
                            ScientificName = "Lens culinaris"
                        },
                        new
                        {
                            Id = 14,
                            Category = "Oilseed",
                            Description = "Rabi oilseed crop.",
                            Name = "Mustard",
                            ScientificName = "Brassica campestris"
                        },
                        new
                        {
                            Id = 15,
                            Category = "Oilseed",
                            Description = "Oilseed crop suitable for both Rabi and Kharif.",
                            Name = "Sunflower",
                            ScientificName = "Helianthus annuus"
                        },
                        new
                        {
                            Id = 16,
                            Category = "Oilseed",
                            Description = "Kharif oilseed crop, primarily grown in Punjab and KP.",
                            Name = "Groundnut",
                            ScientificName = "Arachis hypogaea"
                        },
                        new
                        {
                            Id = 17,
                            Category = "Cash Crop",
                            Description = "Cash crop primarily grown in KP.",
                            Name = "Tobacco",
                            ScientificName = "Nicotiana tabacum"
                        },
                        new
                        {
                            Id = 18,
                            Category = "Fruit",
                            Description = "Important fruit crop of Sindh and Balochistan.",
                            Name = "Date Palm",
                            ScientificName = "Phoenix dactylifera"
                        },
                        new
                        {
                            Id = 19,
                            Category = "Fruit",
                            Description = "Major fruit crop of Balochistan and northern areas.",
                            Name = "Apple",
                            ScientificName = "Malus domestica"
                        },
                        new
                        {
                            Id = 20,
                            Category = "Cereal",
                            Description = "Rabi cereal, used for animal feed and food.",
                            Name = "Barley",
                            ScientificName = "Hordeum vulgare"
                        });
                });

            modelBuilder.Entity("SABZ.Domain.Entities.District", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("NameUrdu")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("ProvinceId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProvinceId");

                    b.ToTable("Districts");
                });

            modelBuilder.Entity("SABZ.Domain.Entities.Farm", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("DistrictId")
                        .HasColumnType("int");

                    b.Property<string>("FarmName")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<decimal>("FarmSize")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<string>("FarmSizeUnit")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("IrrigationType")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal?>("Latitude")
                        .HasPrecision(18, 10)
                        .HasColumnType("decimal(18,10)");

                    b.Property<decimal?>("Longitude")
                        .HasPrecision(18, 10)
                        .HasColumnType("decimal(18,10)");

                    b.Property<int>("ProvinceId")
                        .HasColumnType("int");

                    b.Property<string>("SoilType")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("TehsilId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("DistrictId");

                    b.HasIndex("ProvinceId");

                    b.HasIndex("TehsilId");

                    b.HasIndex("UserId");

                    b.ToTable("Farms");
                });

            modelBuilder.Entity("SABZ.Domain.Entities.Province", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("NameUrdu")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.ToTable("Provinces");
                });

            modelBuilder.Entity("SABZ.Domain.Entities.RegionalCropSuitability", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CropCatalogId")
                        .HasColumnType("int");

                    b.Property<int?>("DistrictId")
                        .HasColumnType("int");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("ProvinceId")
                        .HasColumnType("int");

                    b.Property<string>("Season")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Source")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("SuitabilityLevel")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("SuitabilityScore")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CropCatalogId");

                    b.HasIndex("DistrictId");

                    b.HasIndex("ProvinceId");

                    b.ToTable("RegionalCropSuitabilities");
                });

            modelBuilder.Entity("SABZ.Domain.Entities.Tehsil", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DistrictId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("NameUrdu")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("DistrictId");

                    b.ToTable("Tehsils");
                });

            modelBuilder.Entity("SABZ.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("Email")
                        .HasMaxLength(320)
                        .HasColumnType("nvarchar(320)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("PreferredLanguage")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("English");

                    b.Property<string>("Role")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("Farmer");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasFilter("[Email] IS NOT NULL");

                    b.HasIndex("PhoneNumber")
                        .IsUnique()
                        .HasFilter("[PhoneNumber] IS NOT NULL");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("SABZ.Domain.Entities.Crop", b =>
                {
                    b.HasOne("SABZ.Domain.Entities.CropCatalog", "CropCatalog")
                        .WithMany()
                        .HasForeignKey("CropCatalogId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("SABZ.Domain.Entities.Farm", "Farm")
                        .WithMany("Crops")
                        .HasForeignKey("FarmId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CropCatalog");

                    b.Navigation("Farm");
                });

            modelBuilder.Entity("SABZ.Domain.Entities.District", b =>
                {
                    b.HasOne("SABZ.Domain.Entities.Province", "Province")
                        .WithMany("Districts")
                        .HasForeignKey("ProvinceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Province");
                });

            modelBuilder.Entity("SABZ.Domain.Entities.Farm", b =>
                {
                    b.HasOne("SABZ.Domain.Entities.District", "District")
                        .WithMany()
                        .HasForeignKey("DistrictId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SABZ.Domain.Entities.Province", "Province")
                        .WithMany()
                        .HasForeignKey("ProvinceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SABZ.Domain.Entities.Tehsil", "Tehsil")
                        .WithMany()
                        .HasForeignKey("TehsilId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SABZ.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("District");

                    b.Navigation("Province");

                    b.Navigation("Tehsil");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SABZ.Domain.Entities.RegionalCropSuitability", b =>
                {
                    b.HasOne("SABZ.Domain.Entities.CropCatalog", "CropCatalog")
                        .WithMany("RegionalSuitabilities")
                        .HasForeignKey("CropCatalogId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SABZ.Domain.Entities.District", "District")
                        .WithMany()
                        .HasForeignKey("DistrictId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("SABZ.Domain.Entities.Province", "Province")
                        .WithMany()
                        .HasForeignKey("ProvinceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CropCatalog");

                    b.Navigation("District");

                    b.Navigation("Province");
                });

            modelBuilder.Entity("SABZ.Domain.Entities.Tehsil", b =>
                {
                    b.HasOne("SABZ.Domain.Entities.District", "District")
                        .WithMany("Tehsils")
                        .HasForeignKey("DistrictId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("District");
                });

            modelBuilder.Entity("SABZ.Domain.Entities.CropCatalog", b =>
                {
                    b.Navigation("RegionalSuitabilities");
                });

            modelBuilder.Entity("SABZ.Domain.Entities.District", b =>
                {
                    b.Navigation("Tehsils");
                });

            modelBuilder.Entity("SABZ.Domain.Entities.Farm", b =>
                {
                    b.Navigation("Crops");
                });

            modelBuilder.Entity("SABZ.Domain.Entities.Province", b =>
                {
                    b.Navigation("Districts");
                });
#pragma warning restore 612, 618
        }
    }
}
